### ISSUE TITLE
Adding ionic-platform-web-client plugin stops app from loading in emulators and on devices

### ISSUE THREAD

**Issue by arcadia168** [driftyco/ionic-platform-web-client#63] opened 2016-02-28 11:16 UTC
Hi,

Firstly thanks for the amazing framework again, the fact that this is mostly free is tremendous.

Unfortunately I'm experiencing an issue whereby when attempting to set up push notifications for my project for a good few hours, I get the impression that by adding the ionic-platform-web-client plugin to my app, it will no longer load on emulators or devices.

I tested this theory by moving over my code to a new project (copying 'www' directory, package.json files etc.) and the new projects (I did this multiple times) all worked as expected until I ran:

`ionic add ionic-platform-web-client
`

When running in XCode for more detailed console logs, there are no errors but app just hangs at splash screen:

```
2016-02-28 11:21:46.698 GreyMatter[2451:3634417] Apache Cordova native platform version 4.0.1 is starting.
2016-02-28 11:21:46.699 GreyMatter[2451:3634417] Multi-tasking -> Device: YES, App: YES
2016-02-28 11:21:47.334 GreyMatter[2451:3634417] Using UIWebView
2016-02-28 11:21:47.336 GreyMatter[2451:3634417] [CDVTimer][handleopenurl] 0.066996ms
2016-02-28 11:21:47.339 GreyMatter[2451:3634417] [CDVTimer][intentandnavigationfilter] 3.066003ms
2016-02-28 11:21:47.339 GreyMatter[2451:3634417] [CDVTimer][gesturehandler] 0.096977ms
2016-02-28 11:21:47.406 GreyMatter[2451:3634417] [CDVTimer][splashscreen] 66.531003ms
2016-02-28 11:21:47.406 GreyMatter[2451:3634417] [CDVTimer][TotalPluginStartup] 70.665002ms
2016-02-28 11:21:47.417 GreyMatter[2451:3634417] active
2016-02-28 11:21:47.418 GreyMatter[2451:3634417] PushPlugin skip clear badge
2016-02-28 11:21:49.086 GreyMatter[2451:3634417] Resetting plugins due to page load.
```

I also tested this same assumption against adding the phonegap-plugin-push, but that was fine (was added to the project but never used), and the app still loaded in emulators and devices.

I've successfully implemented push notifications in a previous Ionic application, and think perhaps updates to various tools may be the cause of the issue.

Does anyone have any advice with how to get my app working in emulators and on devices again, and has anyone else experienced a similar issue?

Kind regards,

Ben Nawaz

Ionic information:

```
Your system information:

Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Version: 1.1.0
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
ios-deploy version: 1.8.5 
ios-sim version: 5.0.6 
OS: Mac OS X El Capitan
Node Version: v4.2.4
Xcode version: Xcode 7.2.1 Build version 7C1002 
```

I feel like my problems may be related to [this issue here](https://forum.ionicframework.com/t/push-notifications-problem-as-of-february-2016-new-problem-because-of-updating/42887) which seems very similar but unfortunately has no real solution.

**Comment by ericb** [comment] 2016-02-29 13:09
This could potentially be the push plugin + web client in combination with a specific config variable set on your application. If you plan to use push functionality in an emulator / browser, you need to make sure it's using our 'fake push' functionality, which is enabled with `ionic config set dev_push true` -- You can disable it again when running on an actual device.

Ideally I'd like this to happen automatically or just log a message saying it's temp disabled while in an emulator or browser (the plugin cannot function in the browser, and you can't register tokens in the emulator).

**Comment by warner-pinz** [comment] 2016-03-30 03:02
@ericb  How do we add ionic-platform-web-client in Ionic 2 application?
What is the command to execute to add this plugin? Thanks

**Comment by djangojack** [comment] 2016-03-30 03:40
@warner-pinz they started working on an ionic2 branch, but its not currently ready.
https://github.com/driftyco/ionic-platform-web-client/tree/ionic2-support

**Comment by Fuiste** [comment] 2016-03-31 21:23
As @ericb stated, this is likely an issue with attempting to use native push notifications in an emulator.

As I cannot reproduce this issue when `dev_push` is set to `true` on any of my devices, I"m closing this for now.  Feel free to reopen with a reproduction case if the problem persists.

**Closed by Fuiste** 2016-03-31 21:23 UTC

**Comment by arcadia168** [comment] 2016-04-01 06:49
No problem, thanks for your help, I never resolved the issue but I found that simply porting my www directory to a new project entirely seemed to do the trick, so I can only assume perhaps another of my (third party) Cordova plugins may have been to blame.
