### ISSUE TITLE
injection of $ionicPush fail when dev_push is set to false

### ISSUE THREAD

**Issue by brunosmartin** [driftyco/ionic-platform-web-client#34] opened 2015-12-07 00:09 UTC
if I do:
ionic config set dev_push true

It work just perfect, but if I set:
ionic config set dev_push false

I get (I'm sure that The phonegap-plugin-push is installed!):
```
Ionic Push: PushNotification plugin is required. Have you run `ionic plugin add phonegap-plugin-push` ?error @ ionic.io.bundle.js:3264_getPushPlugin @ ionic.io.bundle.js:5670init @ ionic.io.bundle.js:5296init @ services.js:170(anonymous function) @ controllers.js:119invoke @ ionic.bundle.js:13282instantiate @ ionic.bundle.js:13290(anonymous function) @ ionic.bundle.js:17846self.appendViewElement @ ionic.bundle.js:52338switcher.render @ ionic.bundle.js:50456switcher.init @ ionic.bundle.js:50376self.render @ ionic.bundle.js:52198self.register @ ionic.bundle.js:52156updateView @ ionic.bundle.js:57577(anonymous function) @ ionic.bundle.js:57554Scope.$broadcast @ ionic.bundle.js:24997$state.transition.resolved.then.$state.transition @ ionic.bundle.js:44841processQueue @ ionic.bundle.js:23399(anonymous function) @ ionic.bundle.js:23415Scope.$eval @ ionic.bundle.js:24678Scope.$digest @ ionic.bundle.js:24489Scope.$apply @ ionic.bundle.js:24783done @ ionic.bundle.js:19196completeRequest @ ionic.bundle.js:19368requestLoaded @ ionic.bundle.js:19309
ionic.io.bundle.js:3243 Ionic Push: register
ionic.bundle.js:21162 ReferenceError: PushNotification is not defined
    at ionic.io.bundle.js:5388
    at Push.onReady (ionic.io.bundle.js:5687)
    at Push.register (ionic.io.bundle.js:5379)
    at init (services.js:202)
    at new <anonymous> (controllers.js:119)
    at invoke (ionic.bundle.js:13282)
    at Object.instantiate (ionic.bundle.js:13290)
    at ionic.bundle.js:17846
    at self.appendViewElement (ionic.bundle.js:52338)
    at Object.switcher.render (ionic.bundle.js:50456)
```

The phonegap-plugin-push is installed!

**Comment by ericb** [comment] 2015-12-07 15:02
You may need to rebuild the platform by removing it:

`ionic platform rm android`

and then adding it again:

`ionic platform add android`

If that does not help and you're certain the plugin is installed, you may not be waiting for cordova plugins to be ready.

**Comment by abdoutelb** [comment] 2015-12-15 15:38
same problem here :(

**Comment by ricardobylife** [comment] 2015-12-20 04:08
Same problem. I removed de android platform e added again, but nothing.
Any Ideia?
this is my code:
```
$ionicPlatform.ready(function() {
    // Hide the accessory bar by default (remove this to show the accessory bar above the keyboard
    // for form inputs)
    if (window.cordova && window.cordova.plugins && window.cordova.plugins.Keyboard) {
      cordova.plugins.backgroundMode.enable();
      var push = new Ionic.Push({
        "onNotification": function(notification) {
          alert('Teste push received!'); 
          console.log(notification);
        },
        "pluginConfig": {
          "android": {
            "iconColor": "#FFC900"
          }
        }
      });
    }
  });
```

**Comment by juanluis04** [comment] 2015-12-23 16:30
I have the same problem, even it works fine in Android, when I try to run in iOS this problem occurs even in the physical device. This is an issue....

**Comment by alswamy** [comment] 2015-12-31 09:13
I have the same issue.

**Comment by Fuiste** [comment] 2016-01-25 19:55
Hey everyone, this issue is almost always caused by one of three things:

* You may have a copy of the old [PushPlugin](https://github.com/phonegap-build/PushPlugin) installed, which is deprecated and directly conflicts with [phonegap-plugin-push](https://github.com/phonegap/phonegap-plugin-push)
* You may have an old copy of `ionic-service-core` or `ionic-service-push` installed, which are no longer used by ionic and are not written to use the new push plugin.  These can be safely removes, as their functionality is now contained within the platform web client.
* If you're running the app inside Ionic View or an emulator of any kind, the push plugin will not work.

I've built an app from scratch using Ionic Push with a registration similar to @ricardobylife and cannot reproduce the issue, so I'm going to close this for now.  If someone has a reliable way to reproduce the issue, I'll gladly reopen.

**Closed by Fuiste** 2016-01-25 19:55 UTC

**Comment by warner-pinz** [comment] 2016-03-26 11:06
@Fuiste  @ricardobylife I'm having the same error with Ionic 2.
I could not integrate push notification. If you could shed some light on how to integrate push notification with ionic 2, that would help a lot of us here.
Thank you

`EXCEPTION: ReferenceError: Ionic is not definedBrowserDomAdapter.logError 
app.bundle.js:34288 ReferenceError: Ionic is not defined`

**Comment by aptarmy** [comment] 2016-06-01 02:09
@Fuiste Thanks a lot :) YEEEEPPPEEEE. Now the problem was solved. Now my Android device can receive notifications. For those who are struggling terribly, the following steps are what I did and have my app working.
1. I updated ionic to the latest version and tried creating new blank app using the command `ionic start testPush blank`
2. I also change my app profile setting on app.ionic.io to **production** (Settings -> Certificates)
3. follow this instructions carefully [Full Setup Tutorial]( http://docs.ionic.io/docs/push-full-setup) and [Setup Android Push Profiles](http://docs.ionic.io/v2.0.0-beta/docs/android-push-profiles)
4. After I finished setting up my app, I tested it on Browser using `ionic serve` and it thrown error like push plugin hasn't yet been defined, which cause the registration failed. What I did after that was to **run it on a real device** and every thing works fine. My Android device can register and show its token which I can send notifications to my Android device using Postman.

Hope it helps
